apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ruy2
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0013-tenant/tkrw-pr712-0075-0013-app/devfile-sample-ruy2@sha256:a3dccc7c68e5284b740a30c7879fbcb2ff857fcc0fd3460ec01197aa94a5f689
        name: my-nodejs
        resources: {}
status: {}
